#!/bin/sh

# Lock the screen by default
lock &

# Keyboard daemon
sxhkd &

# Setup monitors
bspc monitor DP-2    -d 3 4 5 6 8
bspc monitor DP-1    -d 1 2 4 5 6 9 10
bspc monitor DVI-D-1 -d 4 5 6 7

# Gaps and border
bspc config border_width 3
bspc config window_gap   12

# Misc options
bspc config split_ratio             0.52
bspc config pointer_follows_monitor true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config top_monocle_padding     12
bspc config pointer_motion_interval 7
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action3         resize_side

# Simple rules for certain applications
bspc rule -a Quodlibet desktop='10' follow=on
bspc rule -a Spotify   desktop='10' follow=on
bspc rule -a discord   desktop='9'
bspc rule -a vlc       desktop='8'
bspc rule -a feh       state=floating
bspc rule -a Eog       state=floating
bspc rule -a MEGAsync  state=floating
bspc rule -a MEGAsync  monitor='DVI-D-1'

# Set the keyboard layout properly and change cursor to not be the X
setxkbmap -layout gb
xsetroot  -cursor_name left_ptr
xset -b

killall redshift
redshift -l 52:0 &

picom -b -c -C -G --shadow-exclude 'class_g = "Rofi"'
wal -R

# Launch polybar
$HOME/.config/polybar/launch
setsid megasync &

