#!/bin/env bash

# To make a lockscreen image because it has to be the exact resolution. i3lock won't downscale images
# convert -resize 1920x1080 source_image Lockscreen.png

i3lock --indicator -kt -i "$HOME/Pictures/Lockscreen.png" \
    --pass-media-keys --pass-screen-keys --pass-power-keys \
    --time-font="Noto Sans CJK JP" --date-font="Noto Sans CJK JP" --ring-width 10 \
    --datesize=20 --timesize=30 --timepos="ix:iy-20" --datepos="ix:iy+30" \
    --radius 110 --timestr="%k : %M" --datestr="%a %d %B" --noinputtext="[Input Empty]" \
    --veriftext="[Verifying]" --wrongtext="[Incorrect]" \
    --timecolor=#FFFFFFFF --datecolor=#FFFFFFFF --verifcolor=#FFFFFFFF --wrongcolor=#FFFFFFFF \
    --insidecolor=#555555FF --ringcolor=#888888FF --line-uses-inside \
    --insidevercolor=#3B6064FF --ringvercolor=#5E7C80FF \
    --insidewrongcolor=#D64933FF --ringwrongcolor=#E17A6AFF \
    --keyhlcolor=#56E39FFF --bshlcolor=#ED6F5BFF --separatorcolor=#888888FF \

