#!/usr/bin/env bash

help() {
    echo "Usage:"
    echo "mediactl [-h][next/prev/toggle]"
    echo "Help Options:"
    echo "  -h: Show this message"
    echo "Commands:"
    echo "  next:   Play next song"
    echo "  prev:   Play previous song"
    echo "  toggle: Toggle Play or pause"
    echo "  play:   Plays the active music player"
    echo "  pause:  Pauses the active music player"
    echo "  stop:   Pauses the player and removes the last player"    
    exit 2
}

exec 2>/dev/null

if [ "$1" = "-h" ]; then
    help
fi

if [ "$(playerctl -l)" = "" ]; then
	echo " No Players are open"
	exit 0
fi

if [ ! -f "/tmp/lastplayer" ]; then
    oldplayer=""
else
    oldplayer=`cat /tmp/lastplayer`
fi

for p in $(playerctl -l);
do
    if [ "$(playerctl -p $p status)" = "Playing" ]; then
        player="$p"
        break
    fi
done

if [[ "$player" = "" && "$oldplayer" = "" ]]; then
    echo " Not Currently Playing"
    exit 0
elif [ "$player" = "" ]; then
    player="$oldplayer"
    if [ "$(playerctl -p $player status)" = "Not available" ];
    then
		echo " Not Currently Playing"
		exit 0
	fi
fi
 
if [ "$1" = "next" ]; then
    playerctl -p $player next
elif [ "$1" = "prev" ]; then
    playerctl -p $player previous
elif [ "$1" = "toggle" ]; then
    playerctl -p $player play-pause
elif [ "$1" = "play" ]; then
    playerctl -p $player play
elif [ "$1" = "pause" ]; then
    playerctl -p $player pause
elif [ "$1" = "stop" ]; then
    playerctl -p $player stop
    rm /tmp/lastplayer
    echo " Not Currently Playing"
    exit 0
elif [ ! "$1" = "" ]; then
    echo "Error: Unknown argument \"$1\""
    help
fi

title=`exec playerctl -p $player metadata xesam:title`
artist=`exec playerctl -p $player metadata xesam:artist`

stat=$(playerctl --player=$player status)
case "$stat" in
	Playing)
		  status=""
		  ;;
	Paused)
		  status=""
		  ;;
	Stopped)
		  status=""
		  ;;
esac

output="$status $artist - $title"

if [[ "$artist" == "" && "$title" == "" ]]; then
    output=" Nothing Playing"
elif [ "$artist" == "" ]; then
    output="Unknown Artist - $title"
elif [ "$title" == "" ]; then
    output="$artist - Unknown Title"
fi

echo "$output"


if [ ! "$player" = "$oldplayer" ]; then
    echo "${player}" > /tmp/lastplayer
fi

