#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait for them to stop
while pgrep -x polybar > /dev/null; do sleep 1; done

# Launch Bar
polybar DesktopLeft &
# TODO
# polybar DesktopRight &

echo "Bars Launched!"
