#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait for them to stop
while pgrep -x polybar > /dev/null; do sleep 1; done

# Launch Bar
if [ "$HOSTNAME" == "Kanto" ]
then
    # Running on desktop
    polybar -c "$HOME/.config/polybar/kanto.config" kanto_left  &
    polybar -c "$HOME/.config/polybar/kanto.config" kanto_middle &
    polybar -c "$HOME/.config/polybar/kanto.config" kanto_right &
elif [ "$HOSTNAME" == "Tokyo" ]
then
    # Running on Laptop
    polybar Laptop &
else
    echo "Unknown Device!"
fi

if [[ -f "$HOME/.fehbg" ]];
then
    "$HOME/.fehbg"
fi

echo "Bars Launched!"
