#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait for them to stop
while pgrep -x polybar > /dev/null; do sleep 1; done

# Launch Bar
if [ "$HOSTNAME" == "Kanto" ]
then
    # Running on desktop
    polybar DesktopLeft &
    polybar DesktopRight &
elif [ "$HOSTNAME" == "Tokyo" ]
then
    # Running on Laptop
    polybar Laptop &
else
    echo "Unknown Device!"
fi


echo "Bars Launched!"
